language: node_js
node_js:
- '5'
branches:
  only:
  - master
install: npm install -g gitbook-cli
before_script: gitbook install
script: gitbook build
after_success:
- bash deploy.sh
env:
  global:
  - GH_REF: github.com/beader/geekbook.git
  - secure: UbeOzcSI8e/Z/RYIiv6VEUkZljS/V2hnE0PP1FiqYVR0Numy2Nda2A8SdUoi0BNTODHcqd5CH2i9k5O/FOLbr5C9Gw0vtr8VGlESbEyX5wkwBiiTVf6NaVQ+yvwkSoowxywdB1I8JtHOmD74bl5Z4H5kTiZ4wAOt0bl3JTjICaOq9l95RUq5zC1p26myyhmo/U/TUKbZY0HWSTJvrkeIFKYx/jisFnrWk/Rx4D+Oh4MkikCO5dI+M1FTEzrm+rpjcMvTM5CjmYgd4SZfAqEkkv0ywgCzQiPThM8UmePJrGRNzwOIf1903RNag7FN3MyxH//h5pC66E+m/w1dB5g1VJA61Y84j/FFeBxt3VqNyf3fS/Z33kkOItDSOgGHuvF92WO8blZhFIJsy6UK0Dte3ljjoTtDIyriuL5lqgvx1rqYRtRlssPvxNPk1PESEfYok/G0GHuGmH/ns1QFPX3607k8BnmMx+7lMVhwravar4uGRzsTPVzHoXUpY644r9Zt5gm2Qsjkz5nPvuv17HaWUjW/X3zLsX2PRy3LSIrg2VT6U/U5fieK8Z8NbmjfJonAr/WJlj3ZKSU8XrCAKtMCsVt6Bd5S6Zvf6t76NZgr4bAJq1WAQB0n2w3GMzSpCKprD0k8Dy1332fnmwRAeS0Cuz5HEII4Xm8BBRh/43YOz1k=
  - secure: izEyxxaghHlvnfnsmse27PUAR9gHC15Xq6NPymKLYFAu8iag8FrFYGjuPgyLsW+tT8cgVIz1logSOJdtK4NSzU4DoZ97D4SNF3xazw7EO4EyTWJckZ68TS907GCb6MPzrMAImCLYih7rFNZ6eZVwNYWngGGLlir0DVrhZp3uE0LQylLw19xoKmtA9PqYi5G64G88+0yZsnxBJj5O8hzJffR77XLr4/QVwONi/fkhD7KIy8jBB75LUeuqMTUBfQKmk1oUgZ8/ZXITAj9WdpcGp193yKGw4py13OTZv1MrjxmvHhQxsR5DU3QxmCf3IdyPVX4im8QntbLUIiKl4XAenrfLzuPPA1zgpTtVZ4i9XZuAFLJRGNVxCGjjTBE5971uqiZhgFr7u0cXamhozUm1m3BQaRIVH+ZjJk9XF1k/ubJtI++CvazTOR+Qwx2XzvSJ5/zkTZMSu2YchMPRse99c4Z0NRoUN6DiURM1V8/lmJnBbxvw3rYVEGL67WGHP5SYHuDvDyJCP4r+AgNO4RMDKz9yL602bItO2PO+C7PeKWSjQCrlbE18gG0ji6AkjyOpZRSNn1oNWOpyWGVjFXRMf2QAd0iyhyr8nWLzv6HFojLr2uS8ZYQ/iD4RkfwGwd+7oGJ2WMxn1cpOycIo+PtPLyVjaUDhWr+xttgCG1tLTlE=
